[package]
name = "mslang"
version = "0.1.0"
edition = "2021"
description = "mslang scripting language implementation"

[dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "1"
parking_lot = "0.12"
libloading = { version = "0.8", optional = true }

[[bin]]
name = "ms"
path = "src/main.rs"

[features]
capi = ["dep:libloading"]

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
cbindgen = "0.26"
cc = "1.0"
