#ifndef MSLANG_CLASS_H
#define MSLANG_CLASS_H

/* Generated with cbindgen:0.26.0 */

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 导入递归深度上限：防 N 层线性依赖链栈溢出（§5）。
 */
#define MAX_IMPORT_DEPTH 200

/**
 * 调用栈最大深度（对齐 Python 默认；task 28/31/36/37/70 共用此常量）。
 */
#define MAX_CALL_DEPTH 1000

/**
 * 大对象阈值：超过则进入 LES 独立分配。
 */
#define LARGE_OBJ_THRESHOLD (32 * 1024)

/**
 * 默认晋升年龄。
 */
#define DEFAULT_PROMOTION_AGE 2

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * C 原生函数签名（与 types.h 中 `MsCFunction` 对应）。
 * `Option` 表示可为 NULL（C 侧）。MsVM 为不透明指针，使用裸指针类型。
 */
typedef MsValue *(*MsCFunction)(MsVM*, MsValue*const *, int32_t);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
struct MsFuncDef {
    const char *name;
    MsCFunction func;
};
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
struct MsConstDef {
    const char *name;
    MsValue *val;
};
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
struct MsModuleDef {
    const char *name;
    const struct MsFuncDef *methods;
    const struct MsConstDef *consts;
};
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * C 异步函数签名（与 types.h 中 `MsAsyncFunction` 对应）。
 * `Option` 表示可为 NULL（C 侧）。task 76 完整实现桥接；task 72 仅占位。
 */
typedef void (*MsAsyncFunction)(MsVM*, MsValue*const *, int32_t, MsValue*);
#endif

MS_API MsValue *msGetClass(MsVM *vm, const int8_t *name);

MS_API MsValue *msInstanceNew(MsVM *vm, MsValue *cls, MsValue *const *args, int nargs);

MS_API MsValue *msInstanceGet(MsVM *vm, MsValue *obj, const int8_t *attr);

MS_API MsStatus msInstanceSet(MsVM *vm, MsValue *obj, const int8_t *attr, MsValue *val);

MS_API int msIsInstance(MsVM *vm, MsValue *obj, MsValue *cls);

MS_API MsValue *msClassDefine(MsVM *vm, const int8_t *name, MsValue *parent);

MS_API MsStatus msClassAddMethod(MsVM *vm, MsValue *cls, const int8_t *name, MsCFunction method);

MS_API MsStatus msClassAddStatic(MsVM *vm, MsValue *cls, const int8_t *name, MsValue *val);

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsVM *msVmNew(void);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msVmFree(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msAddModulePath(MsVM *vm, const int8_t *path);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msSetArgs(MsVM *vm, int32_t argc, const int8_t *const *argv);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msSetStdout(MsVM *vm, MsWriteFn fn_ptr, void *userdata);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msSetStderr(MsVM *vm, MsWriteFn fn_ptr, void *userdata);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msExecFile(MsVM *vm, const int8_t *path);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msExecString(MsVM *vm, const int8_t *source, const int8_t *filename);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msEval(MsVM *vm, const int8_t *expr);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msGetGlobal(MsVM *vm, const int8_t *name);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msSetGlobal(MsVM *vm, const int8_t *name, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msDelGlobal(MsVM *vm, const int8_t *name);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msVmLock(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msVmUnlock(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 释放 C 侧持有的 MsValue。NULL 安全。
 * 注意：仅释放 Box<MsValue> 包装，不释放 inner Object 引用的堆对象（由 GC 管理）。
 */
MS_API
void msValueFree(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建 Nil 值。每次调用返回新 Box（内联值，无需 GC 管理）。
 */
MS_API MsValue *msNil(void);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建 Bool 值。val != 0 → true，val == 0 → false。
 */
MS_API MsValue *msBoolVal(int val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建 Int 值（不依赖 VM）。
 */
MS_API MsValue *msInt(int64_t val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建 Float 值（不依赖 VM）。
 */
MS_API MsValue *msFloat(double val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从 C 空终止字符串创建 String 值。等价于 msStringn(vm, str, strlen(str))。
 * str 为 NULL 时创建空字符串。
 */
MS_API MsValue *msString(MsVM *vm, const char *str);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从指定长度的字节创建 String 值（可包含 `\0`）。
 * str 为 NULL 或 len == 0 时创建空字符串。
 */
MS_API MsValue *msStringn(MsVM *vm, const char *str, uintptr_t len);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建空 List。
 */
MS_API MsValue *msListNew(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建空 Dict。
 */
MS_API MsValue *msDictNew(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建空 Set。
 */
MS_API MsValue *msSetNew(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从数组创建 List。NULL 元素被跳过。
 */
MS_API MsValue *msListFrom(MsVM *vm, MsValue *const *items, int count);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从数组创建 Tuple。NULL 元素被跳过。
 */
MS_API MsValue *msTupleFrom(MsVM *vm, MsValue *const *items, int count);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从扁平 key-value 数组创建 Dict。count 为键值对数量（数组长度 = count * 2）。
 * NULL key 或 value 对应的键值对被跳过。
 */
MS_API MsValue *msDictFrom(MsVM *vm, MsValue *const *pairs, int count);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回值类型的 MsType 枚举。NULL 安全（返回 Nil）。
 */
MS_API MsType msTypeof(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsNil(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsBool(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsInt(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsFloat(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsNumber(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsString(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsList(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsDict(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsTuple(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsSet(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * msIsFunction 对 FUNCTION 和 CLOSURE 均返回 MS_TRUE。
 */
MS_API int msIsFunction(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsClass(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsGenerator(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsFuture(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsChannel(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从 MsValue 提取 i64。Int → i64；Float → 截断（NaN/Inf 设 TypeError 返回 0）；
 * 其余设 TypeError 返回 0。NULL 安全。
 */
MS_API int64_t msToInt(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从 MsValue 提取 f64。Int/Float → f64；其余设 TypeError 返回 0.0。NULL 安全。
 */
MS_API double msToFloat(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 按 truthy 规则转换为 MS_TRUE/MS_FALSE。不设异常。NULL 安全。
 */
MS_API int msToBool(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回内部字符串指针（借用引用）。所有类型格式化到 thread_local 缓冲区
 * （保证 null 终止符）。NULL 安全。
 */
MS_API const char *msToString(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回字符串副本（CString::into_raw），C 侧 free() 释放。NULL 安全。
 */
MS_API char *msToStringCopy(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 对应 mslang int()。Bool→0/1；Int→自身；Float→截断；String→解析。
 * 转换失败设 TypeError 返回 NULL。NULL 安全。
 */
MS_API MsValue *msConvertInt(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 对应 mslang float()。Bool→0.0/1.0；Int→f64；Float→自身；String→解析。
 * 转换失败设 TypeError 返回 NULL。NULL 安全。
 */
MS_API MsValue *msConvertFloat(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 对应 mslang str()。所有类型用 Display 格式化；String→自身。
 * NULL 安全。
 */
MS_API MsValue *msConvertStr(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 对应 mslang bool()。按 truthy 规则返回 MS_TRUE_VAL/MS_FALSE_VAL。
 * NULL 安全。
 */
MS_API MsValue *msConvertBool(MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 对应 mslang list()。String→字符列表；List→浅拷贝；Tuple/Set→转换；
 * Dict→key 列表。其余报错。NULL 安全。
 */
MS_API MsValue *msConvertList(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 值相等比较（==）。返回 MS_TRUE/MS_FALSE。NULL 安全。
 */
MS_API int msEq(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 顺序比较 a < b。类型不兼容设 TypeError。NULL 安全。
 */
MS_API int msLt(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 顺序比较 a <= b。类型不兼容设 TypeError。NULL 安全。
 */
MS_API int msLe(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 顺序比较 a > b。类型不兼容设 TypeError。NULL 安全。
 */
MS_API int msGt(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 顺序比较 a >= b。类型不兼容设 TypeError。NULL 安全。
 */
MS_API int msGe(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 身份比较（is）。对 Ref 类型比较指针；内联值返回 MS_FALSE
 * （签名无 vm 参数，无法设 TypeError）。NULL 安全。
 */
MS_API int msIs(MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回哈希值。不可哈希类型设异常返回 0。NULL 安全。
 */
MS_API int64_t msHash(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取命名属性。Deferred（Task 73）：Instance/Module/Class。
 * 其余类型设 TypeError 返回 NULL。NULL 安全。
 */
MS_API MsValue *msGetAttr(MsVM *vm, MsValue *obj, const char *attr);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置命名属性。Deferred（Task 73）：仅 Instance 和可变对象支持。
 * 其余类型设 TypeError 返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msSetAttr(MsVM *vm, MsValue *obj, const char *attr, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取下标。Deferred（Task 69）：List/Dict/String/Tuple。
 * 其余类型设 TypeError 返回 NULL。NULL 安全。
 */
MS_API MsValue *msGetItem(MsVM *vm, MsValue *obj, MsValue *key);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置下标。Deferred（Task 69）：仅 List 和 Dict 支持。
 * 其余类型设 TypeError 返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msSetItem(MsVM *vm, MsValue *obj, MsValue *key, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 通用长度。String/List/Dict/Tuple/Set 返回元素数；其余设异常返回 -1。
 * NULL 安全。
 */
MS_API int64_t msLen(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 repr 字符串。String 带引号，对象显示类型信息。NULL 安全。
 */
MS_API MsValue *msRepr(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回字符串 UTF-8 字节长度。NULL 安全。
 */
MS_API uintptr_t msStringLen(MsVM *vm, MsValue *str_val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回内部 UTF-8 数据指针（借用引用，无需 free）。NULL 安全。
 */
MS_API const char *msStringData(MsVM *vm, MsValue *str_val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 连接两个字符串，返回新字符串。NULL 安全。
 */
MS_API MsValue *msStringConcat(MsVM *vm, MsValue *a, MsValue *b);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 字符串切片，支持负索引。按字节切片。NULL 安全。
 */
MS_API MsValue *msStringSlice(MsVM *vm, MsValue *str_val, int start, int end);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 List 长度。非 List 返回 -1。NULL 安全。
 */
MS_API int msListLen(MsVM *vm, MsValue *list);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取 List 元素（支持负索引）。越界设异常返回 NULL。NULL 安全。
 */
MS_API MsValue *msListGet(MsVM *vm, MsValue *list, int index);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 原地修改指定位置（支持负索引）。越界设异常返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msListSet(MsVM *vm, MsValue *list, int index, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 尾部追加元素，返回 MS_OK。NULL 安全。
 */
MS_API MsStatus msListPush(MsVM *vm, MsValue *list, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 弹出末尾元素并返回。空列表设异常返回 NULL。NULL 安全。
 */
MS_API MsValue *msListPop(MsVM *vm, MsValue *list);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 在指定位置插入元素（支持负索引）。NULL 安全。
 */
MS_API MsStatus msListInsert(MsVM *vm, MsValue *list, int index, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 包含则返回 MS_TRUE，否则 MS_FALSE。NULL 安全。
 */
MS_API int msListContains(MsVM *vm, MsValue *list, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建新列表切片，支持负索引和 step。step=0 设异常返回 NULL。NULL 安全。
 */
MS_API MsValue *msListSlice(MsVM *vm, MsValue *list, int start, int end, int step);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 Dict 长度。非 Dict 返回 -1。NULL 安全。
 */
MS_API int msDictLen(MsVM *vm, MsValue *dict);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取键对应的值。键不存在返回 NULL（不设异常）。NULL 安全。
 */
MS_API MsValue *msDictGet(MsVM *vm, MsValue *dict, MsValue *key);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取键对应的值，不存在时返回 defaultVal。NULL 安全。
 */
MS_API MsValue *msDictGetDefault(MsVM *vm, MsValue *dict, MsValue *key, MsValue *default_val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置键值对（存在则覆盖）。键不可哈希设异常返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msDictSet(MsVM *vm, MsValue *dict, MsValue *key, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 删除键值对。键不存在设异常返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msDictRemove(MsVM *vm, MsValue *dict, MsValue *key);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 包含则返回 MS_TRUE，否则 MS_FALSE。NULL 安全。
 */
MS_API int msDictContains(MsVM *vm, MsValue *dict, MsValue *key);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回新 List，包含所有键（保持插入顺序）。NULL 安全。
 */
MS_API MsValue *msDictKeys(MsVM *vm, MsValue *dict);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回新 List，包含所有值（保持插入顺序）。NULL 安全。
 */
MS_API MsValue *msDictValues(MsVM *vm, MsValue *dict);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回新 List，每个元素为二元 Tuple (key, value)。NULL 安全。
 */
MS_API MsValue *msDictItems(MsVM *vm, MsValue *dict);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 Tuple 长度。非 Tuple 返回 -1。NULL 安全。
 */
MS_API int msTupleLen(MsVM *vm, MsValue *tup);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 获取 Tuple 元素（支持负索引）。越界设异常返回 NULL。NULL 安全。
 */
MS_API MsValue *msTupleGet(MsVM *vm, MsValue *tup, int index);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 解包 Tuple，通过 malloc 分配 MsValue* 数组。调用方用 msTupleUnpackFree 释放。
 */
MS_API MsStatus msTupleUnpack(MsVM *vm, MsValue *tup, MsValue ***items_out, int *count_out);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 释放 msTupleUnpack 分配的数组（逐个释放 MsValue + 数组本身）。
 */
MS_API void msTupleUnpackFree(MsValue **items, int count);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 Set 长度。非 Set 返回 -1。NULL 安全。
 */
MS_API int msSetLen(MsVM *vm, MsValue *set);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 添加元素（已存在则无操作）。不可哈希设异常返回 MS_ERROR。NULL 安全。
 */
MS_API MsStatus msSetAdd(MsVM *vm, MsValue *set, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 删除元素。不存在时无异常、无错误（返回 MS_OK）。NULL 安全。
 */
MS_API MsStatus msSetRemove(MsVM *vm, MsValue *set, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 包含则返回 MS_TRUE，否则 MS_FALSE。NULL 安全。
 */
MS_API int msSetContains(MsVM *vm, MsValue *set, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 调用可迭代对象的 __iter__ 协议。当前为占位实现，设 TypeError 返回 NULL。
 */
MS_API MsValue *msIter(MsVM *vm, MsValue *iterable);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 调用迭代器的 __next__。当前为占位实现，返回 MS_ERROR。
 */
MS_API MsStatus msNext(MsVM *vm, MsValue *iterator, MsValue **out);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 调用可调用对象，返回结果（新引用）。异常时返回 NULL。
 *
 * func 必须是可调用对象（Function、Closure、BoundMethod、C 原生函数，
 * 或带 `__call__` 的 Instance）。可调用性由 VM `call_value` 内部 match 处理。
 */
MS_API MsValue *msCall(MsVM *vm, MsValue *func, MsValue *const *args, int nargs);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 将 C 函数指针包装为 VM 可调用对象（MsValue*）。
 * 返回的值可作为全局变量注册，供 mslang 脚本调用。
 */
MS_API MsValue *msMakeCFunction(MsVM *vm, const char *name, MsCFunction func, int arity);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 异步调用：包装 func 为协程，立即返回 Future（Pending 或 Resolved 状态）。
 * 协程在 EventLoop 中执行；func 完成时 EventLoop 自动 resolve/reject Future。
 *
 * msCallAsync 在返回前驱动 EventLoop（pump），使不挂起的协程立即完成。
 */
MS_API MsValue *msCallAsync(MsVM *vm, MsValue *func, MsValue *const *args, int nargs);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 阻塞等待 Future 完成。
 * - Resolved → 返回结果（新引用）
 * - Rejected → 设置异常，返回 NULL
 * - Pending → 驱动 EventLoop（单线程模式）；若仍 Pending，Condvar 等待（多线程模式）
 */
MS_API
MsValue *msAwait(MsVM *vm,
                 MsValue *future);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsFutureState msFutureState(MsVM *vm, MsValue *future);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 将 Future 设为 Resolved 并唤醒所有等待者（协程 + 线程）。幂等。
 */
MS_API void msFutureResolve(MsVM *vm, MsValue *future, MsValue *result);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 将 Future 设为 Rejected 并唤醒所有等待者。error 自动包装为 RuntimeError MsException。幂等。
 */
MS_API
void msFutureReject(MsVM *vm,
                    MsValue *future,
                    MsValue *error);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 创建指定缓冲区大小的 Channel 对象。buffer_size 须在 0-255 范围内。
 */
MS_API MsValue *msChannel(MsVM *vm, int buffer_size);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 发送值到 Channel。缓冲区满时线程级阻塞。
 */
MS_API MsStatus msChannelSend(MsVM *vm, MsValue *ch, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 从 Channel 接收值。缓冲区空时线程级阻塞；Channel 已关闭且为空时返回 nil。
 */
MS_API
MsValue *msChannelRecv(MsVM *vm,
                       MsValue *ch);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 关闭 Channel（幂等）。唤醒所有等待的协程与线程。
 */
MS_API MsStatus msChannelClose(MsVM *vm, MsValue *ch);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 查询 Channel 是否已关闭。
 */
MS_API int msChannelIsClosed(MsVM *vm, MsValue *ch);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 Generator 的迭代器（Generator 自身即为迭代器，返回新引用）。
 */
MS_API MsValue *msGeneratorIter(MsVM *vm, MsValue *generator);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 恢复 Generator 执行，获取下一个 yield 值。
 * MS_OK 时 *out 设置为 yield 值（新引用）；
 * MS_ERROR 时迭代结束（无异常）或运行时错误（has_error=true）。
 */
MS_API MsStatus msGeneratorNext(MsVM *vm, MsValue *generator, MsValue **out);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msErrOccurred(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msErrFetch(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API void msErrClear(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API const char *msErrTypeName(MsVM *_vm, MsValue *err);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API const char *msErrMessage(MsVM *_vm, MsValue *err);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API const char *msErrTraceback(MsVM *_vm, MsValue *err);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msErrCause(MsVM *_vm, MsValue *err);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrow(MsVM *vm, const char *type_, const char *fmt);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowValue(MsVM *vm, MsValue *err);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowRethrow(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowTypeError(MsVM *vm, const char *expected, const char *actual);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowValueError(MsVM *vm, const char *fmt);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowIndexError(MsVM *vm, const char *fmt);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowKeyError(MsVM *vm, MsValue *key);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowRuntimeError(MsVM *vm, const char *fmt);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msThrowIoError(MsVM *vm, const char *fmt);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msTry(MsVM *vm, MsValue *func, MsValue *const *args, int nargs, MsValue **result);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msRegisterModule(MsVM *vm, const struct MsModuleDef *def);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msModuleNew(MsVM *vm, const char *name);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msModuleAddFunc(MsVM *vm, MsValue *mod_val, const char *name, MsCFunction fn_ptr);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API
MsStatus msModuleAddAsyncFunc(MsVM *vm,
                              MsValue *mod_val,
                              const char *name,
                              MsAsyncFunction fn_ptr);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msModuleAddConst(MsVM *vm, MsValue *mod_val, const char *name, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msRegisterModuleValue(MsVM *vm, MsValue *mod_val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msGetClass(MsVM *vm, const int8_t *name);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msInstanceNew(MsVM *vm, MsValue *cls, MsValue *const *args, int nargs);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msInstanceGet(MsVM *vm, MsValue *obj, const int8_t *attr);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msInstanceSet(MsVM *vm, MsValue *obj, const int8_t *attr, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API int msIsInstance(MsVM *vm, MsValue *obj, MsValue *cls);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsValue *msClassDefine(MsVM *vm, const int8_t *name, MsValue *parent);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msClassAddMethod(MsVM *vm, MsValue *cls, const int8_t *name, MsCFunction method);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
MS_API MsStatus msClassAddStatic(MsVM *vm, MsValue *cls, const int8_t *name, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 将对象注册为 GC 根，返回 `val` 本身。注册后 GC 不会回收此对象。
 * 仅对 Ref 类型（堆对象）有效。内联值为安全 no-op。NULL 安全。
 */
MS_API MsValue *msRoot(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 注销 GC 根。注销后对象可能被 GC 回收。
 * 仅对 Ref 类型（堆对象）有效。内联值为安全 no-op。NULL 安全。
 */
MS_API void msUnroot(MsVM *vm, MsValue *val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 写屏障。task 77 升级为委托 VM 内部 `write_barrier_obj`（Go 1.8+ 风格混合写屏障）。
 *
 * **保守近似**：C API 签名 `msWriteBarrier(vm, parent, new_val)` 缺少 `old_val` 参数
 * （13-capi.md:642 已固化），故仅走插入屏障侧（shade new_val）+ 无条件 card marking，
 * 不走删除屏障侧（无法 shade 被覆盖的旧值）。详见 task 77 § 写屏障。
 *
 * 行为：
 * - 非并发标记阶段：仅 card marking（Old parent → Young new_val，开销极小），着色逻辑返回。
 * - 并发标记阶段：额外将 White 的 new_val 原子标灰 + 入灰色队列。
 *
 * 仅对 Ref 类型（堆对象）有效；内联值（Int/Float/Bool/Nil）为安全 no-op。NULL 安全。
 */
MS_API
void msWriteBarrier(MsVM *vm,
                    MsValue *parent,
                    MsValue *new_val);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 注册 C finalizer 回调。对象被 GC 回收前在 mutator 线程中调用回调。
 * MsFinalizerFn 签名：`void (*)(MsVM* vm, MsValue* obj, void* userdata)`。
 *
 * 失败时（vm/obj 为 NULL、obj 非 Ref 类型、fn 为 NULL）返回 MS_ERROR。
 */
MS_API
MsStatus msOnFinalize(MsVM *vm,
                      MsValue *obj,
                      void (*fn_ptr)(MsVM*, MsValue*, void*),
                      void *userdata);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 按 MsGcType 触发 GC（Minor / Major / Full）。手动触发不受 gc_enabled 影响。
 */
MS_API void msGcCollect(MsVM *vm, MsGcType gc_type);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 启用（enable=1）或禁用（enable=0）自动 GC。
 */
MS_API void msGcEnable(MsVM *vm, int32_t enable);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回当前自动 GC 状态（1=启用，0=禁用）。
 */
MS_API int32_t msGcIsEnabled(MsVM *vm);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置 GC 触发阈值。
 * - MS_GC_MAJOR / MS_GC_FULL：threshold 为 Old GC 触发比率
 * - MS_GC_MINOR：threshold 为 Young 代大小（MB），clamp [0.5, 64.0]
 */
MS_API void msGcSetThreshold(MsVM *vm, MsGcType gc_type, double threshold);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置晋升年龄（1-3，超出范围被 clamp）。默认值为 2。
 */
MS_API void msGcSetPromotionAge(MsVM *vm, uint32_t age);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 设置 GC 线程数。task 77 升级：写入 `heap.gc_threads_setting`，下次并发 GC 周期 Init
 * 阶段（`init_concurrent_mark`）读取此字段写入 `gc_runtime.gc_threads`（AtomicU32），
 * 供 Coordinator 启动 Worker 池。当前周期不生效。
 *
 * clamp 到 `gc_threads_max()`（CPU 核数上限），与脚本侧 `gc.set_gc_threads` 一致
 * （Task 64 C5）。Task 64 自适应调整可能在下次 GC 收尾单调上调此值。
 */
MS_API
void msGcSetGcThreads(MsVM *vm,
                      uint32_t threads);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 启用/禁用 GC 调试模式。仅 debug_assertions 构建中有实际效果。
 */
MS_API void msGcSetDebug(MsVM *vm, int32_t enable);
#endif

#if (defined(MS_CAPI_ENABLED) && defined(MS_CAPI_ENABLED))
/**
 * 返回 GC 统计快照。NULL vm 返回全零 MsGcStats。
 *
 * task 77：扩展并发 GC 指标。从 `MsHeap`（mutator 独占字段）+ `GcRuntime`
 * （Arc deref 原子 load）直接组装——无 `MsHeap::get_stats()` 方法（沿用 Task 74 模式）。
 *
 * `gc_threads`：并发模式（`concurrent_enabled=true`）返回 `gc_runtime.gc_threads` 真实值；
 * 降级模式（默认）返回 1（STW 单线程实际值）。
 */
MS_API
MsGcStats msGcStats(MsVM *vm);
#endif

#endif /* MSLANG_CLASS_H */
