#ifndef MSLANG_GENERATED_H
#define MSLANG_GENERATED_H

/* Generated with cbindgen:0.26.0 */

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 导入递归深度上限：防 N 层线性依赖链栈溢出（§5）。
 */
#define MAX_IMPORT_DEPTH 200

/**
 * 调用栈最大深度（对齐 Python 默认；task 28/31/36/37/70 共用此常量）。
 */
#define MAX_CALL_DEPTH 1000

/**
 * 大对象阈值：超过则进入 LES 独立分配。
 */
#define LARGE_OBJ_THRESHOLD (32 * 1024)

/**
 * 默认晋升年龄。
 */
#define DEFAULT_PROMOTION_AGE 2

#endif /* MSLANG_GENERATED_H */
