#ifndef MSLANG_H
#define MSLANG_H

#include "types.h"

 /* The following headers are generated by cbindgen from src/capi/ modules.
  * They will be uncommented as each API module is implemented.
  */

 #include "vm.h"

 #include "error.h"

 #include "module.h"

 /* #include "class.h"
    * #include "gc.h"
    */
#include "class.h"
#include "gc.h"

#include "call_macros.h"

#endif /* MSLANG_H */
