#ifndef MS_TYPES_H
#define MS_TYPES_H

#include <stdint.h>
#include <stddef.h>

/* ── Version ── */

#define MS_VERSION_MAJOR  0
#define MS_VERSION_MINOR  1
#define MS_VERSION_PATCH  0
#define MS_VERSION        "0.1.0"

#define MS_VERSION_AT_LEAST(major, minor, patch)              \
    (MS_VERSION_MAJOR > (major) ||                             \
     (MS_VERSION_MAJOR == (major) && MS_VERSION_MINOR > (minor)) || \
     (MS_VERSION_MAJOR == (major) && MS_VERSION_MINOR == (minor) && \
      MS_VERSION_PATCH >= (patch)))

/* ── Platform macros ── */

/* R2: MS_BUILDING is only defined when building mslang.dll itself (Rust side
 * #[no_mangle] pub extern "C" handles dllexport automatically, no C macro
 * needed). C extension modules do NOT define MS_BUILDING (they use dllimport
 * to link against mslang.dll). */
#ifdef _WIN32
  #ifdef MS_BUILDING
    #define MS_API __declspec(dllexport)
  #else
    #define MS_API __declspec(dllimport)
  #endif
#else
  #define MS_API __attribute__((visibility("default")))
#endif

#ifdef _WIN32
  #define MS_MODULE_INIT __declspec(dllexport)
#else
  #define MS_MODULE_INIT __attribute__((visibility("default")))
#endif

/* ── Opaque types ── */

typedef struct MsVM MsVM;
typedef struct MsValue MsValue;

/* ── Function pointer types ── */

typedef MsValue* (*MsCFunction)(MsVM* vm, MsValue* const* args, int nargs);
typedef void (*MsAsyncFunction)(MsVM* vm, MsValue* const* args, int nargs,
    MsValue* future);
typedef void (*MsFinalizerFn)(MsVM* vm, MsValue* obj, void* userdata);
/* L1: MsWriteFn is used by vm.h's msSetStdout/msSetStderr (13-capi.md:167).
 * Defined here in the hand-written types.h so that the cbindgen-generated
 * vm.h can reference it. */
typedef int (*MsWriteFn)(const char* data, size_t len, void* userdata);

/* ── Enums ── */

/* V4 note: MsType and the internal TypeTag (14-gc.md:89-112) are different
 * enums. MsType includes inline types like Nil/Bool/Float; TypeTag only
 * contains heap types (STRING=1, LIST=2, ...). Their numeric values do not
 * correspond; the conversion mapping is done by the match in task 67's
 * msTypeof implementation. */
typedef enum MsType {
    MS_TYPE_NIL          = 0,
    MS_TYPE_BOOL         = 1,
    MS_TYPE_INT          = 2,
    MS_TYPE_FLOAT        = 3,
    MS_TYPE_STRING       = 4,
    MS_TYPE_LIST         = 5,
    MS_TYPE_DICT         = 6,
    MS_TYPE_TUPLE        = 7,
    MS_TYPE_SET          = 8,
    MS_TYPE_FUNCTION     = 9,
    MS_TYPE_CLASS        = 10,
    MS_TYPE_INSTANCE     = 11,
    MS_TYPE_MODULE       = 12,
    MS_TYPE_GENERATOR    = 13,
    MS_TYPE_FUTURE       = 14,
    MS_TYPE_CHANNEL      = 15,
    MS_TYPE_ITERATOR     = 16,
    MS_TYPE_BOUND_METHOD = 17,
    MS_TYPE_JOIN_HANDLE  = 18,
} MsType;

typedef enum MsStatus {
    MS_OK    =  0,
    MS_ERROR = -1,
    MS_YIELD =  1,
} MsStatus;

typedef enum MsGcType {
    MS_GC_MINOR = 0,
    MS_GC_MAJOR = 1,
    MS_GC_FULL  = 2,
} MsGcType;

typedef enum MsFutureState {
    MS_FUTURE_PENDING  = 0,
    MS_FUTURE_RESOLVED = 1,
    MS_FUTURE_REJECTED = 2,
} MsFutureState;

/* L5: MsFutureState is in the call.h section in 13-capi.md; this task moves it
 * forward into the hand-written types.h so that the cbindgen-generated call.h
 * can reference this enum (13-capi.md:433-437). */

/* L2: MsGcStats is the return value of task 74's msGcStats (13-capi.md:678-687).
 * Defined here in the hand-written types.h in advance to avoid a missing type
 * dependency when cbindgen generates gc.h.
 *
 * task 77：追加 6 个并发 GC 指标字段于末尾（前 8 字段偏移不变 → forward-compatible）。
 * sizeof 从 64→112 字节；嵌入方若用 sizeof 做内存布局需重新编译。 */
typedef struct MsGcStats {
    uint64_t minorGcCount;
    uint64_t majorGcCount;
    uint64_t totalPauseNs;
    uint64_t lastPauseNs;
    uint64_t youngSize;
    uint64_t oldSize;
    uint64_t losSize;
    uint64_t bytesFreed;
    /* task 77：并发 GC 指标 */
    uint64_t concurrentMarkNs;  /* 并发标记阶段耗时（纳秒） */
    uint64_t concurrentSweepNs; /* 并发清扫阶段耗时（纳秒） */
    uint64_t initStwNs;         /* Init STW 阶段耗时（纳秒） */
    uint64_t termStwNs;         /* Mark Termination STW 阶段耗时（纳秒） */
    uint64_t grayQueuePeak;     /* 灰色队列峰值大小 */
    uint64_t gcThreads;         /* 当前 GC Worker 线程数 */
} MsGcStats;

/* L6: MsFuncDef/MsConstDef/MsModuleDef structs are generated by cbindgen from
 * Rust #[repr(C)] structs (task 72 module.h); no need to hand-write them here. */

/* ── Boolean constants ── */

#define MS_TRUE  1
#define MS_FALSE 0

#endif /* MS_TYPES_H */
